import { defineConfig } from "vite";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import path from "node:path";

// The vendored build is a self-contained ESM file with no externals.
//
// Output goes to dist-kanban-core/, not dist/: the app's own `vite build`
// targets outDir "dist" with emptyOutDir true (vite.config.ts), which would
// wipe this file if the two builds shared a directory.

const pkg = JSON.parse(readFileSync(path.resolve(__dirname, "package.json"), "utf8")) as { version: string };

type GitState = {
	commit: string;
	shortCommit: string;
	dirty: boolean;
};

function gitOutput(args: string[], state: string): string {
	try {
		return execFileSync("git", args, {
			cwd: __dirname,
			encoding: "utf8",
			stdio: ["ignore", "pipe", "pipe"],
		}).trim();
	} catch (cause) {
		throw new Error(`Cannot build portable kanban artifacts without an exact Git ${state}.`, { cause });
	}
}

function readGitState(): GitState {
	const commit = gitOutput(["rev-parse", "--verify", "HEAD^{commit}"], "source commit");
	if (!/^(?:[0-9a-f]{40}|[0-9a-f]{64})$/i.test(commit)) {
		throw new Error(`Cannot build portable kanban artifacts: Git returned an invalid commit "${commit}".`);
	}

	return {
		commit,
		shortCommit: commit.slice(0, 8),
		dirty: gitOutput(["status", "--porcelain", "--untracked-files=normal"], "working-tree state").length > 0,
	};
}

function banner(libraryName: string, git: GitState): string {
	const description = libraryName === "kanban-client"
		? "Portable jKanban 1.3.1 + Dragula 3.7.3 client; see PROVENANCE.json and bundled licences."
		: "Minimal vendored adopt coordinator from mise-en-place's src/kanban-core; see docs/kanban-core-contract.md.";
	return `/*!
 * ${libraryName} v${pkg.version} (${git.shortCommit}${git.dirty ? "-dirty" : ""})
 * ${description}
 * Generated by \`npm run build:${libraryName}\`. Do not edit.
 */`;
}

export default defineConfig(({ mode }) => {
	const client = mode === "kanban-client";
	const libraryName = client ? "kanban-client" : "kanban-core";
	const git = readGitState();

	return {
		publicDir: client ? path.resolve(__dirname, "src/kanban-component/licenses") : false,
		plugins: [{
				name: "kanban-provenance",
				enforce: "post" as const,
				generateBundle: {
					order: "post" as const,
					handler(_options, bundle) {
						const provenance = (client ? JSON.parse(readFileSync(
							path.resolve(__dirname, "src/kanban-component/PROVENANCE.json"),
							"utf8",
						)) : {
							 source: { repository: "joe-butler-23/mise-en-place", commit: "", dirty: true, entry: "src/kanban-core/adopt-entry.ts" },
							artifact: { format: "es", javascript: "kanban-core.mjs", stylesheet: "", files: [] },
						}) as {
							source: { repository: string; commit: string; dirty: boolean; entry: string };
							artifact: {
								format: string;
								javascript: string;
								stylesheet: string;
								files: Array<{ path: string; bytes: number; sha256: string }>;
							};
						};
						provenance.source.commit = git.commit;
						provenance.source.dirty = git.dirty;
						provenance.artifact.files = Object.values(bundle)
							.filter((output) => output.fileName.endsWith(".mjs") || output.fileName.endsWith(".css"))
							.map((output) => {
								const bytes = Buffer.from(output.type === "chunk" ? output.code : output.source);
								return {
									path: output.fileName,
									bytes: bytes.byteLength,
									sha256: createHash("sha256").update(bytes).digest("hex"),
								};
							})
							.sort((left, right) => left.path.localeCompare(right.path));
						this.emitFile({
							type: "asset",
							fileName: "PROVENANCE.json",
							source: `${JSON.stringify(provenance, null, 2)}\n`,
						});
					},
				},
			}],
		build: {
			outDir: `dist-${libraryName}`,
			emptyOutDir: true,
			target: "esnext",
			minify: client,
			lib: {
				entry: path.resolve(__dirname, client ? "src/kanban-component/client.ts" : "src/kanban-core/adopt-entry.ts"),
				formats: ["es"],
				fileName: () => `${libraryName}.mjs`,
				...(client && { cssFileName: libraryName }),
			},
			rolldownOptions: {
				output: {
					banner: banner(libraryName, git),
				},
			},
		},
	};
});
